# Generated by Django 4.2.6 on 2023-10-29 10:33

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_rename_product_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Catagory',
            new_name='catagory',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=shops.models.getFileName),
        ),
    ]
